import { useState, useEffect } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import {
    AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent,
    AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Plus, FileText, Search, Download, Trash2, Send, CheckCircle2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { supabaseCRM } from "@/integrations/supabase/crm-client";
import { toast } from "sonner";
import type { Factura } from "@/types/crm";

export default function Facturas() {
    const [facturas, setFacturas] = useState<Factura[]>([]);
    const [loading, setLoading] = useState(true);
    const [search, setSearch] = useState("");
    const [filtroEstado, setFiltroEstado] = useState("todos");
    const [dialogOpen, setDialogOpen] = useState(false);
    const [deleteId, setDeleteId] = useState<string | null>(null);
    const [clientes, setClientes] = useState<any[]>([]);
    const [presupuestos, setPresupuestos] = useState<any[]>([]);

    const [form, setForm] = useState({
        cliente_id: "",
        presupuesto_id: "",
        titulo: "",
        notas: "",
        items: [{ descripcion: "", cantidad: "1", precio_unitario: "", total: "" }],
    });

    useEffect(() => { loadFacturas(); loadClientes(); }, []);

    const loadFacturas = async () => {
        try {
            const { data: { user } } = await supabase.auth.getUser();
            if (!user) return;
            const { data, error } = await supabaseCRM
                .from("facturas")
                .select("*, clientes(nombre, empresa)")
                .eq("usuario_id", user.id)
                .order("created_at", { ascending: false });
            if (error) throw error;
            setFacturas(data || []);
        } catch { toast.error("Error cargando facturas"); }
        finally { setLoading(false); }
    };

    const loadClientes = async () => {
        const { data } = await supabase.from("clientes").select("id, nombre, empresa").order("nombre");
        setClientes(data || []);
    };

    const loadPresupuestos = async (clienteId: string) => {
        const { data } = await supabase
            .from("presupuestos")
            .select("id, numero, titulo, total, items_presupuesto(*)")
            .eq("cliente_id", clienteId)
            .eq("estado", "aprobado")
            .order("created_at", { ascending: false });
        setPresupuestos(data || []);
    };

    const handlePresupuestoSelect = (presupuestoId: string) => {
        const p = presupuestos.find((pr) => pr.id === presupuestoId);
        if (p) {
            const items = (p.items_presupuesto || []).map((item: any) => ({
                descripcion: item.descripcion,
                cantidad: String(item.cantidad),
                precio_unitario: String(item.precio_unitario),
                total: String(item.total),
            }));
            setForm({ ...form, presupuesto_id: presupuestoId, titulo: `Factura - ${p.titulo}`, items: items.length > 0 ? items : form.items });
        }
    };

    const calcTotal = () => form.items.reduce((sum, item) => sum + (parseFloat(item.total) || 0), 0);

    const updateItem = (index: number, field: string, value: string) => {
        const newItems = [...form.items];
        newItems[index] = { ...newItems[index], [field]: value };
        if (field === "cantidad" || field === "precio_unitario") {
            const cant = parseFloat(newItems[index].cantidad) || 0;
            const precio = parseFloat(newItems[index].precio_unitario) || 0;
            newItems[index].total = String(cant * precio);
        }
        setForm({ ...form, items: newItems });
    };

    const handleCreate = async () => {
        if (!form.cliente_id || !form.titulo || form.items.length === 0) {
            toast.error("Cliente, título e items son obligatorios");
            return;
        }
        try {
            const { data: { user } } = await supabase.auth.getUser();
            if (!user) return;

            const subtotal = calcTotal();
            const ivaMonto = subtotal * 0.19;

            const { data: factura, error } = await supabaseCRM.from("facturas").insert({
                usuario_id: user.id,
                cliente_id: form.cliente_id,
                presupuesto_id: form.presupuesto_id || null,
                numero: "", // auto-generated by trigger
                titulo: form.titulo,
                subtotal,
                iva_porcentaje: 19,
                iva_monto: ivaMonto,
                total: subtotal + ivaMonto,
                notas: form.notas || null,
            }).select().single();

            if (error) throw error;

            // Insert items
            const itemsToInsert = form.items.filter(i => i.descripcion).map((item, idx) => ({
                factura_id: factura.id,
                descripcion: item.descripcion,
                cantidad: parseFloat(item.cantidad) || 1,
                precio_unitario: parseFloat(item.precio_unitario) || 0,
                total: parseFloat(item.total) || 0,
                orden: idx,
            }));

            if (itemsToInsert.length > 0) {
                const { error: itemsError } = await supabaseCRM.from("items_factura").insert(itemsToInsert);
                if (itemsError) throw itemsError;
            }

            toast.success("Factura creada correctamente");
            setDialogOpen(false);
            setForm({ cliente_id: "", presupuesto_id: "", titulo: "", notas: "", items: [{ descripcion: "", cantidad: "1", precio_unitario: "", total: "" }] });
            loadFacturas();
        } catch (e: any) { toast.error("Error: " + e.message); }
    };

    const handleStatusChange = async (id: string, newStatus: string) => {
        const { error } = await supabaseCRM.from("facturas").update({ estado: newStatus }).eq("id", id);
        if (error) toast.error("Error actualizando");
        else { toast.success("Estado actualizado"); loadFacturas(); }
    };

    const handleDelete = async () => {
        if (!deleteId) return;
        const { error } = await supabaseCRM.from("facturas").delete().eq("id", deleteId);
        if (error) toast.error("Error eliminando");
        else { toast.success("Factura eliminada"); setDeleteId(null); loadFacturas(); }
    };

    const filtered = facturas.filter((f) => {
        const matchSearch = f.numero?.toLowerCase().includes(search.toLowerCase()) ||
            f.titulo?.toLowerCase().includes(search.toLowerCase()) ||
            f.clientes?.nombre?.toLowerCase().includes(search.toLowerCase());
        const matchEstado = filtroEstado === "todos" || f.estado === filtroEstado;
        return (search === "" || matchSearch) && matchEstado;
    });

    const PAGE_SIZE = 10;
    const [page, setPage] = useState(1);
    const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
    const paginated = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);

    const getEstadoBadge = (estado: string) => {
        switch (estado) {
            case "borrador": return <Badge variant="secondary">Borrador</Badge>;
            case "enviada": return <Badge className="bg-blue-500/20 text-blue-400 border-blue-500/30">Enviada</Badge>;
            case "pagada": return <Badge className="bg-green-500/20 text-green-400 border-green-500/30">Pagada</Badge>;
            case "vencida": return <Badge className="bg-red-500/20 text-red-400 border-red-500/30">Vencida</Badge>;
            case "cancelada": return <Badge className="bg-gray-500/20 text-gray-400 border-gray-500/30">Cancelada</Badge>;
            default: return <Badge variant="secondary">{estado}</Badge>;
        }
    };

    const totalFacturado = facturas.reduce((s, f) => s + Number(f.total), 0);
    const totalPagado = facturas.filter(f => f.estado === "pagada").reduce((s, f) => s + Number(f.total), 0);
    const totalPendiente = facturas.filter(f => ["enviada", "borrador"].includes(f.estado)).reduce((s, f) => s + Number(f.total), 0);

    return (
        <DashboardLayout>
            <div className="space-y-6 animate-in fade-in duration-500">
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                    <div>
                        <h1 className="text-3xl font-bold tracking-tight">Facturas</h1>
                        <p className="text-muted-foreground mt-1">Emite y gestiona facturas para tus clientes</p>
                    </div>
                    <Button onClick={() => setDialogOpen(true)} className="gap-2 gradient-button">
                        <Plus className="w-4 h-4" /> Nueva Factura
                    </Button>
                </div>

                {/* KPIs */}
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                    <Card className="p-4 border-primary/20 bg-primary/5">
                        <p className="text-xs text-muted-foreground uppercase">Total Facturado</p>
                        <p className="text-2xl font-bold">${totalFacturado.toLocaleString()}</p>
                    </Card>
                    <Card className="p-4 border-green-500/20 bg-green-500/5">
                        <p className="text-xs text-muted-foreground uppercase">Pagado</p>
                        <p className="text-2xl font-bold text-green-400">${totalPagado.toLocaleString()}</p>
                    </Card>
                    <Card className="p-4 border-yellow-500/20 bg-yellow-500/5">
                        <p className="text-xs text-muted-foreground uppercase">Pendiente</p>
                        <p className="text-2xl font-bold text-yellow-400">${totalPendiente.toLocaleString()}</p>
                    </Card>
                </div>

                {/* Filters */}
                <div className="flex flex-col sm:flex-row gap-3">
                    <div className="relative flex-1">
                        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                        <Input placeholder="Buscar por número, título, cliente..." value={search} onChange={(e) => setSearch(e.target.value)} className="pl-9" />
                    </div>
                    <Select value={filtroEstado} onValueChange={setFiltroEstado}>
                        <SelectTrigger className="w-[160px]"><SelectValue placeholder="Estado" /></SelectTrigger>
                        <SelectContent>
                            <SelectItem value="todos">Todos</SelectItem>
                            <SelectItem value="borrador">Borrador</SelectItem>
                            <SelectItem value="enviada">Enviada</SelectItem>
                            <SelectItem value="pagada">Pagada</SelectItem>
                            <SelectItem value="vencida">Vencida</SelectItem>
                            <SelectItem value="cancelada">Cancelada</SelectItem>
                        </SelectContent>
                    </Select>
                </div>

                {/* Table */}
                <Card className="overflow-hidden">
                    <div className="overflow-x-auto">
                        <table className="w-full">
                            <thead>
                                <tr className="border-b border-border bg-muted/30">
                                    <th className="text-left p-3 text-xs font-semibold text-muted-foreground uppercase">Número</th>
                                    <th className="text-left p-3 text-xs font-semibold text-muted-foreground uppercase">Título</th>
                                    <th className="text-left p-3 text-xs font-semibold text-muted-foreground uppercase hidden md:table-cell">Cliente</th>
                                    <th className="text-left p-3 text-xs font-semibold text-muted-foreground uppercase">Total</th>
                                    <th className="text-left p-3 text-xs font-semibold text-muted-foreground uppercase">Estado</th>
                                    <th className="text-left p-3 text-xs font-semibold text-muted-foreground uppercase hidden sm:table-cell">Fecha</th>
                                    <th className="text-right p-3 text-xs font-semibold text-muted-foreground uppercase">Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {loading ? (
                                    <tr><td colSpan={7} className="p-8 text-center text-muted-foreground">Cargando...</td></tr>
                                ) : filtered.length === 0 ? (
                                    <tr><td colSpan={7} className="p-8 text-center text-muted-foreground">No hay facturas</td></tr>
                                ) : (
                                    paginated.map((f) => (
                                        <tr key={f.id} className="border-b border-border/50 hover:bg-accent/5 transition-colors">
                                            <td className="p-3 font-mono text-sm font-bold">{f.numero}</td>
                                            <td className="p-3 text-sm">{f.titulo}</td>
                                            <td className="p-3 text-sm hidden md:table-cell text-muted-foreground">{f.clientes?.nombre}</td>
                                            <td className="p-3 font-bold">${Number(f.total).toLocaleString()}</td>
                                            <td className="p-3">{getEstadoBadge(f.estado)}</td>
                                            <td className="p-3 text-sm text-muted-foreground hidden sm:table-cell">{new Date(f.fecha_emision).toLocaleDateString("es-CL")}</td>
                                            <td className="p-3">
                                                <div className="flex items-center justify-end gap-1">
                                                    {f.estado === "borrador" && (
                                                        <Button size="sm" variant="ghost" className="h-8 text-xs text-blue-400" onClick={() => handleStatusChange(f.id, "enviada")}>
                                                            <Send className="w-3 h-3 mr-1" /> Enviar
                                                        </Button>
                                                    )}
                                                    {f.estado === "enviada" && (
                                                        <Button size="sm" variant="ghost" className="h-8 text-xs text-green-400" onClick={() => handleStatusChange(f.id, "pagada")}>
                                                            <CheckCircle2 className="w-3 h-3 mr-1" /> Pagada
                                                        </Button>
                                                    )}
                                                    <Button size="sm" variant="ghost" className="h-8 text-red-400" onClick={() => setDeleteId(f.id)}>
                                                        <Trash2 className="w-3 h-3" />
                                                    </Button>
                                                </div>
                                            </td>
                                        </tr>
                                    ))
                                )}
                            </tbody>
                        </table>
                    </div>
                    {filtered.length > PAGE_SIZE && (
                        <div className="flex items-center justify-between p-3 border-t border-border/50">
                            <p className="text-xs text-muted-foreground">
                                Mostrando {(page - 1) * PAGE_SIZE + 1}-{Math.min(page * PAGE_SIZE, filtered.length)} de {filtered.length}
                            </p>
                            <div className="flex gap-1">
                                <Button size="sm" variant="outline" disabled={page <= 1} onClick={() => setPage(page - 1)}>Anterior</Button>
                                <Button size="sm" variant="outline" disabled={page >= totalPages} onClick={() => setPage(page + 1)}>Siguiente</Button>
                            </div>
                        </div>
                    )}
                </Card>
            </div>

            {/* Create Dialog */}
            <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
                <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
                    <DialogHeader><DialogTitle>Nueva Factura</DialogTitle></DialogHeader>
                    <div className="space-y-4">
                        <div>
                            <Label>Cliente *</Label>
                            <Select value={form.cliente_id} onValueChange={(v) => { setForm({ ...form, cliente_id: v }); loadPresupuestos(v); }}>
                                <SelectTrigger><SelectValue placeholder="Seleccionar cliente" /></SelectTrigger>
                                <SelectContent>
                                    {clientes.map((c) => <SelectItem key={c.id} value={c.id}>{c.nombre} {c.empresa ? `(${c.empresa})` : ""}</SelectItem>)}
                                </SelectContent>
                            </Select>
                        </div>
                        {presupuestos.length > 0 && (
                            <div>
                                <Label>Importar desde Presupuesto</Label>
                                <Select value={form.presupuesto_id} onValueChange={handlePresupuestoSelect}>
                                    <SelectTrigger><SelectValue placeholder="Seleccionar presupuesto aprobado" /></SelectTrigger>
                                    <SelectContent>
                                        {presupuestos.map((p) => <SelectItem key={p.id} value={p.id}>{p.numero} — ${Number(p.total).toLocaleString()}</SelectItem>)}
                                    </SelectContent>
                                </Select>
                            </div>
                        )}
                        <div>
                            <Label>Título *</Label>
                            <Input value={form.titulo} onChange={(e) => setForm({ ...form, titulo: e.target.value })} placeholder="Ej: Factura desarrollo web" />
                        </div>

                        {/* Items */}
                        <div>
                            <Label>Items</Label>
                            <div className="space-y-2 mt-2">
                                {form.items.map((item, idx) => (
                                    <div key={idx} className="grid grid-cols-12 gap-2">
                                        <Input className="col-span-5" placeholder="Descripción" value={item.descripcion} onChange={(e) => updateItem(idx, "descripcion", e.target.value)} />
                                        <Input className="col-span-2" type="number" placeholder="Cant" value={item.cantidad} onChange={(e) => updateItem(idx, "cantidad", e.target.value)} />
                                        <Input className="col-span-2" type="number" placeholder="Precio" value={item.precio_unitario} onChange={(e) => updateItem(idx, "precio_unitario", e.target.value)} />
                                        <Input className="col-span-2" type="number" placeholder="Total" value={item.total} readOnly />
                                        <Button variant="ghost" size="icon" className="col-span-1 text-red-400" onClick={() => setForm({ ...form, items: form.items.filter((_, i) => i !== idx) })} disabled={form.items.length <= 1}>
                                            <Trash2 className="w-3 h-3" />
                                        </Button>
                                    </div>
                                ))}
                                <Button variant="outline" size="sm" onClick={() => setForm({ ...form, items: [...form.items, { descripcion: "", cantidad: "1", precio_unitario: "", total: "" }] })}>
                                    <Plus className="w-3 h-3 mr-1" /> Agregar Item
                                </Button>
                            </div>
                        </div>

                        <div className="text-right space-y-1 border-t pt-3">
                            <p className="text-sm text-muted-foreground">Subtotal: ${calcTotal().toLocaleString()}</p>
                            <p className="text-sm text-muted-foreground">IVA (19%): ${(calcTotal() * 0.19).toLocaleString()}</p>
                            <p className="text-lg font-bold">Total: ${(calcTotal() * 1.19).toLocaleString()}</p>
                        </div>

                        <div>
                            <Label>Notas</Label>
                            <Textarea value={form.notas} onChange={(e) => setForm({ ...form, notas: e.target.value })} rows={2} />
                        </div>
                    </div>
                    <DialogFooter>
                        <Button variant="outline" onClick={() => setDialogOpen(false)}>Cancelar</Button>
                        <Button onClick={handleCreate} className="gradient-button">Crear Factura</Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>

            {/* Delete Dialog */}
            <AlertDialog open={!!deleteId} onOpenChange={() => setDeleteId(null)}>
                <AlertDialogContent>
                    <AlertDialogHeader>
                        <AlertDialogTitle>¿Eliminar factura?</AlertDialogTitle>
                        <AlertDialogDescription>Esta acción no se puede deshacer.</AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                        <AlertDialogCancel>Cancelar</AlertDialogCancel>
                        <AlertDialogAction onClick={handleDelete} className="bg-red-500 hover:bg-red-600">Eliminar</AlertDialogAction>
                    </AlertDialogFooter>
                </AlertDialogContent>
            </AlertDialog>
        </DashboardLayout>
    );
}
